---
title: www.campnerdly.org
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Your New Jekyll Site
markdown: redcarpet
header: 'Camp Nerdly X: May 19-21, 2017, Prince William Forest Park'
